name: Test
on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize]
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test:coverage
      - name: Upload Coverage
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
